server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://ourmemory.cqlnwevakpwc.ap-northeast-2.rds.amazonaws.com:3306/OurMemory?serverTimezone=UTC
    username: ourmemory
    password: ourmemory
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB
  message:
    basename: i18n/exception
    encoding: UTF-8

custom:
  fcm-key: E:\Git\FCM_ServiceKey.json

cloud:
  aws:
    credentials:
      accessKey: AKIA6AVXSEVS33MJM2VZ
      secretKey: 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
    s3:
      bucket: ourmemory
      profile-image-dir: profileImages
    region:
      static: ap-northeast-2
    stack:
      auto: false
