spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  message:
    basename: i18n/exception
    encoding: UTF-8

cloud:
  aws:
    credentials:
      access-key: ${AccessKey}
      secret-key: ${SecretKey}
    s3:
      bucket: ourmemory
      profile-image-dir: profileImages
    region:
      static: ap-northeast-2
    stack:
      auto: false

custom:
  fcm-key: ${FcmKeyPath}
