server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://kds-ourmemory.cqlnwevakpwc.ap-northeast-2.rds.amazonaws.com:3306/OurMemory?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3307/OurMemory?serverTimezone=UTC
    username: ourmemory
    password: ourmemory
  jpa:
    properties:      hibernate:
        format_sql: true
    hibernate:      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true  mvc:
    throw-exception-if-no-handler-found: true
  resources:    add-mappings: false