version: 0.0
os: linux
files:
  - source: /OurMemory.tgz
    destination: /home/ec2-user/OurMemory/deploy
    overwrite: yes

permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: OurMemory/start.sh
      timeout: 180
      runas: ec2-user