# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle


name: Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'develop'
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [16]

    steps:
      - name: Use JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create Fcm service key file
        run: |
          cd OurMemory_Server/src/main/resources
          touch fcmServiceKey.json
          cat << EOF >> fcmServiceKey.json
          ${{ secrets.FCM_SERVICE_KEY }}

      - name: Echo application-test.yml
        run: echo ${{ secrets.APPLICATION_TEST }}

      - name: Create application-test.yml
        run: |
          cd OurMemory_Server/src/main/resources
          touch application-test.yml
          cat << EOF >> application-test.yml
          ${{ secrets.APPLICATION_TEST }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./OurMemory_Server/gradlew

      - name: Build with gradle
        run: ./gradlew build
        working-directory: ./OurMemory_Server
